spring:
  application:
    name: product-idea-validator
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: 6285316d6080a266f62fb9c164c2112a52f9ea754f63ef37fc877fc5359343a58dbbbc6e
    expiration-ms: 86400000 # 24 giờ
